[package]
name = "rgb"
version = "0.7.0"
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
include = ["src/**/*", "Cargo.toml", "README.md"]
description = "`struct RGB` for sharing pixels between crates.\nAllows no-copy high-level interoperability. Also adds common convenience methods and implements standard Rust traits to make RGB/RGBA pixels first-class Rust objects."
documentation = "https://pornel.github.io/rust-rgb/rgb/"
repository = "https://github.com/pornel/rust-rgb"
readme = "README.md"
keywords = ["rgb", "rgba", "pixel", "interoperability"]
license = "MIT"
categories = ["rust-patterns", "multimedia::images"]

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
