[package]
name = "rgb"
version = "0.5.1"
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
include = ["src/**/*", "Cargo.toml", "README.md"]
description = "struct RGB for sharing pixels between crates"
documentation = "https://pornel.github.io/rust-rgb/rgb/"
repository = "https://github.com/pornel/rust-rgb"
readme = "README.md"
keywords = ["rgb", "rgba", "pixel", "interoperability"]
license = "MIT"

[dependencies]
